apiVersion: apps/v1
kind: Deployment
metadata:
  name: azure-iothub-exporter  
  labels:
    app: azure-iothub-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azure-iothub-exporter
  template:
    metadata:
      labels:
        app: azure-iothub-exporter
    spec:
      containers:
      - name: exporter
        image: {{  .Values.imageName}}:{{  .Values.imageTag}}
        env:                                          
        - name: EVENT_HUB_CONNECTION_STRING
          valueFrom:
            secretKeyRef:
              name: azure-iothub-exporter-secret 
              key: EVENT_HUB_CONNECTION_STRING
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: {{  .Values.containerPort}}
