apiVersion: v1
kind: Secret
metadata:
  name: azure-iothub-exporter-secret
stringData:
  EVENT_HUB_CONNECTION_STRING:  {{ required "Provide a value for eventHubConnectionString" .Values.eventHubConnectionString}}
type: Opaque