apiVersion: v1
kind: Service
metadata:
  name: azure-iothub-exporter
spec:
  selector:
    app: azure-iothub-exporter   
  ports:
    - port: {{  .Values.containerPort}}
      targetPort: {{  .Values.servicePort}}
